### ISSUE TITLE
Issue in Installing

### ISSUE THREAD

**Issue by II-VSB-II** [monitoring-tools/prom-nginx-exporter#11]
Hey, 
Can you provide me the proper commands for installing this exporter.

**Comment by d-ulyanov** [comment]
Hi, Nick! On what platform you're installing nginx exporter?

**Comment by II-VSB-II** [comment]
centos 7.X.

**Comment by II-VSB-II** [comment]
If I am running it as docker container it is working but I want to add nginx url dynamically. In docker it is running as PID 1 bcoz of that I am not able to kill that process. Is there any way I can kill that process add run again with more nginx url.?

**Comment by d-ulyanov** [comment]
You can pass command line arguments to your docker container when you calling docker run ...
Does it work for you?
