### ISSUE TITLE
no nginx or nginx plus stats url specified

### ISSUE THREAD

**Issue by chookhong** [monitoring-tools/prom-nginx-exporter#9]
I'm testing the prom-nginx-exporter and have followed the instruction to make linux build. But when running the prom-nginx-exporter command, an error is shown although both nginx-stats-urls and nginx-plus-stats-urls are defined.

$ ./linux_amd64/prom-nginx-exporter listen-address="localhost:9005" --metrics-path="/metrics" --namespace="nginxplus" --nginx-stats-urls="localhost:9002/status" --nginx-stats-urls="localhost:9003/status" --nginx-plus-stats-urls="localhost:9004/status"
FATA[0000] no nginx or nginx plus stats url specified    source="main.go:38"

**Comment by bartjolenovation** [comment]
when I define the stats url with "http://" it works as expected (or https would work if you use that)

**Comment by chookhong** [comment]
Thanks @bartjolenovation 
It is actually the missing of -- in front of then listen-address flag in the sample command. I just copied and run it without checking.

**Comment by bartjolenovation** [comment]
@chookhong ok can you close this issue?
